In [43]:
import numpy as np

# Задаем значение n
n = 20

# Шаг 1: Создание матрицы n x n, заполненной нулями
step1 = np.zeros((n, n))

# Шаг 2: Заполнение диагонали
diagonal = 1 / np.arange(1, n + 1)
step2 = np.diag(diagonal)

# Шаг 3: Заполнение верхней части матрицы
step3 = np.triu(np.ones((n, n)), 1)

# Шаг 4: Суммирование всех шагов
result = np.flipud(step2) + np.fliplr(step3)

# Вывод промежуточных результатов
print("Шаг 1:\n", step1)
print("Шаг 2:\n",  np.flipud(step2))
print("Шаг 3:\n", np.fliplr(step3))
print("Результат:\n", result)


Шаг 1:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [44]:
import numpy as np

def f(x):
    return 5*x**4 + x**3 + x**2 + 2*x - 2

def localize_roots():
    intervals = []  # Список для хранения интервалов

    # Локализация первого корня
    a1, b1 = -1, 0  # Интервал для первого корня
    intervals.append((a1, b1))

    # Локализация второго корня
    a2, b2 = -2, -1  # Интервал для второго корня
    intervals.append((a2, b2))

    # Локализация третьего корня
    a3, b3 = 0, 1  # Интервал для третьего корня
    intervals.append((a3, b3))

    # Локализация четвертого корня
    a4, b4 = 2, 3  # Интервал для четвертого корня
    intervals.append((a4, b4))

    return intervals

roots_intervals = localize_roots()
print("Локализованные корни уравнения:")
for i, interval in enumerate(roots_intervals, start=1):
    a, b = interval
    print(f"Корень {i}: [{a}, {b}]")


Локализованные корни уравнения:
Корень 1: [-1, 0]
Корень 2: [-2, -1]
Корень 3: [0, 1]
Корень 4: [2, 3]


In [45]:
def phi(x):
    return x - f(x) / (20*x**3 + 3*x**2 + 2*x + 2)

def iterative_process(x0, phi, tolerance=1e-6, max_iterations=100):
    x = x0
    for i in range(max_iterations):
        x_next = phi(x)
        if abs(x_next - x) < tolerance:
            return x_next
        x = x_next
    return None

initial_values = [-0.5, -1.5, 0.5, 2.5]  # Начальные значения для каждого корня

print("\nИтерационные процессы:")
for i, interval in enumerate(roots_intervals, start=1):
    a, b = interval
    x0 = (a + b) / 2  # Выбираем середину интервала как начальное значение
    root = iterative_process(x0, phi)
    print(f"Корень {i}: x = {root}")



Итерационные процессы:
Корень 1: x = -0.9343983070451642
Корень 2: x = -0.934398307045166
Корень 3: x = 0.5463790854936387
Корень 4: x = 0.5463790854936388


In [46]:
import sympy as sp

x = sp.symbols('x')
f = sp.sin(sp.ln(x))
f_prime = f.diff(x)
f_double_prime = f_prime.diff(x)

f_prime_simplified = sp.simplify(f_prime)
f_double_prime_simplified = sp.simplify(f_double_prime)

print(f_prime_simplified)
print(f_double_prime_simplified)


cos(log(x))/x
-sqrt(2)*sin(log(x) + pi/4)/x**2


In [48]:
import math

def f(x):
    return math.sin(math.log(x))

def f_prime(x):
    return math.cos(math.log(x)) / x

def newton_method(x0, f, f_prime, tolerance=1e-6, max_iterations=100):
    x = x0
    iterations = 0

    while abs(f(x)) > tolerance and iterations < max_iterations:
        x = x - f(x) / f_prime(x)
        iterations += 1

    return x

# Определение границ интервала
a = 22
b = 24

# Выбор начального значения x0
if f_prime(a) * f_prime(b) > 0:
    x0 = a
else:
    x0 = b

# Применение итерационного процесса Ньютона
root = newton_method(x0, f, f_prime)
print("Корень уравнения:", root)


Корень уравнения: 23.140676132299564


In [49]:
from scipy.interpolate import lagrange
import numpy as np

def f(x):
    return np.sin(x/np.pi) / x

# Заданные узлы
x_values = [23, 24, 25]
y_values = [f(x) for x in x_values]

# Построение интерполяционного многочлена Лагранжа
lagrange_poly = lagrange(x_values, y_values)

# Вывод интерполяционного многочлена Лагранжа
print("Интерполяционный многочлен Лагранжа:")
print(lagrange_poly)

# Оценка погрешности
x = np.linspace(22, 25, 100)  # Генерация значений x для оценки погрешности
y_true = f(x)  # Значения истинной функции
y_approx = lagrange_poly(x)  # Значения приближенной функции многочленом

# Вычисление погрешности
error = np.abs(y_true - y_approx)

# Вывод максимальной погрешности
max_error = np.max(error)
print("Максимальная погрешность:", max_error)


Интерполяционный многочлен Лагранжа:
           2
-0.002094 x + 0.1017 x - 1.193
Максимальная погрешность: 4.355078014747771e-05


In [50]:
import numpy as np

def f(x):
    return x / (1 + x**2)

def chebyshev_nodes(n, a, b):
    k = np.arange(1, n + 1)
    x_nodes = 0.5 * (a + b) + 0.5 * (b - a) * np.cos((2 * k - 1) * np.pi / (2 * n))
    return x_nodes

def interpolate_chebyshev(f, n, a, b):
    x_nodes = chebyshev_nodes(n, a, b)
    y_nodes = f(x_nodes)
    coeffs = np.polynomial.chebyshev.chebfit(x_nodes, y_nodes, n - 1)
    return coeffs

def evaluate_polynomial(coeffs, x):
    return np.polynomial.chebyshev.chebval(x, coeffs)

epsilon = 1e-3
a = 0
b = 1
n = 2  # Начальное количество узлов

while True:
    coeffs = interpolate_chebyshev(f, n, a, b)
    x_values = np.linspace(a, b, 10)
    y_values = evaluate_polynomial(coeffs, x_values)

    max_error = np.max(np.abs(f(x_values) - y_values))
    if max_error < epsilon:
        break

    n += 1

print("Требуемое количество узлов:", n)
print("Значения узлов:")
x_nodes = chebyshev_nodes(n, a, b)
y_nodes = f(x_nodes)
for i in range(n):
    print(f"Узел {i+1}: x = {x_nodes[i]}, y = {y_nodes[i]}")


Требуемое количество узлов: 5
Значения узлов:
Узел 1: x = 0.9755282581475768, y = 0.49984657482189776
Узел 2: x = 0.7938926261462366, y = 0.48697137076485225
Узел 3: x = 0.5, y = 0.4
Узел 4: x = 0.2061073738537635, y = 0.19770866061143047
Узел 5: x = 0.024471741852423234, y = 0.024457095325922537


In [53]:
import numpy as np

def linear_approximation(x, y):
    n = len(x)
    A = np.vstack([x, np.ones(n)]).T
    m, c = np.linalg.lstsq(A, y, rcond=None)[0]
    return m, c

def quadratic_approximation(x, y):
    n = len(x)
    A = np.vstack([x**2, x, np.ones(n)]).T
    a, b, c = np.linalg.lstsq(A, y, rcond=None)[0]
    return a, b, c

def cubic_approximation(x, y):
    n = len(x)
    A = np.vstack([x**3, x**2, x, np.ones(n)]).T
    a, b, c, d = np.linalg.lstsq(A, y, rcond=None)[0]
    return a, b, c, d

def rms_error(x, y, coefficients):
    n = len(x)
    y_predicted = np.polyval(coefficients, x)
    error = np.sqrt(np.mean((y - y_predicted)**2))
    return error

x = np.array([2, 3, 4, 5, 6])
y = np.array([17.2, 45.5, 96.5, 175.8, 288.9])

# Линейное приближение
m, c = linear_approximation(x, y)
linear_coeffs = [m, c]
linear_error = rms_error(x, y, linear_coeffs)

# Квадратичное приближение
a, b, c = quadratic_approximation(x, y)
quadratic_coeffs = [a, b, c]
quadratic_error = rms_error(x, y, quadratic_coeffs)

# Кубическое приближение
a, b, c, d = cubic_approximation(x, y)
cubic_coeffs = [a, b, c, d]
cubic_error = rms_error(x, y, cubic_coeffs)

# Определение наиболее вероятного типа зависимости
errors = [linear_error, quadratic_error, cubic_error]
min_error = min(errors)
min_error_index = errors.index(min_error)
approximation_types = ['линейная', 'квадратичная', 'кубическая']
most_probable_type = approximation_types[min_error_index]

print("Линейное приближение:", linear_coeffs)
print("Среднеквадратическое отклонение (линейное):", linear_error)
print("Квадратичное приближение:", quadratic_coeffs)
print("Среднеквадратическое отклонение (квадратичное):", quadratic_error)
print("Кубическое приближение:", cubic_coeffs)
print("Среднеквадратическое отклонение (кубическое):", cubic_error)
print("Наиболее вероятный тип зависимости:", most_probable_type)


Линейное приближение: [67.36999999999996, -144.6999999999999]
Среднеквадратическое отклонение (линейное): 23.705606931694444
Квадратичное приближение: [14.135714285714313, -45.71571428571444, 53.20000000000036]
Среднеквадратическое отклонение (квадратичное): 1.5697861546811296
Кубическое приближение: [0.9249999999999963, 3.0357142857143153, -4.46071428571434, 6.579999999999991]
Среднеквадратическое отклонение (кубическое): 0.005345224838241158
Наиболее вероятный тип зависимости: кубическая


In [59]:
import sympy as sp

# Определение переменных
h = sp.Symbol('h')
x0, x1, x2, x3 = 0, 2*h, 4*h, 5*h
y0, y1, y2, y3 = sp.symbols('y0 y1 y2 y3')
c0, c1, c2, c3 = sp.symbols('c0 c1 c2 c3')

# Формула для производной y''(x1) методом неопределенных коэффициентов
y_double_prime = c0*y0 + c1*y1 + c2*y2 + c3*y3

# Система уравнений для определения коэффициентов c0, c1, c2, c3
eq1 = c0 + c1 + c2 + c3
eq2 = c0*(-2*h) + c1*0 + c2*2*h + c3*h - y_double_prime

# Решение системы уравнений
solution = sp.solve([eq1, eq2], (c0, c1, c2, c3))

# Формула для вычисления y''(x1) по значениям функции в узлах
formula = y_double_prime.subs(solution)

# Раскрытие y(xi) в ряд Тейлора
taylor_series = sp.series(formula, h, n=4)

# Определение порядка погрешности O(h^p)
p = taylor_series.as_expr().as_poly(h).degree()

print("Формула для вычисления y''(x1):")
print(formula)
print("Порядок погрешности O(h^p):")
print(p)


AttributeError: 'NoneType' object has no attribute 'degree'

In [62]:
from sympy import symbols, diff

x = symbols('x')
y = x**2 + 3*x + 1

# вычисление второй производной функции
y_double_prime = diff(y, x, 2)
print(y_double_prime)

2


In [63]:
from sympy import symbols, sin

x = symbols('x')
y = sin(x)

# разложение функции в ряд Тейлора до 4 порядка
y_taylor = y.series(x, 0, 4)
print(y_taylor)

x - x**3/6 + O(x**4)
